version: "3.7"
services:
  db:
    container_name: todo-mysql
    image: dw1m2g25/report_dw1_m3:todo-mysql
    command:
      - --character-set-server=utf8mb4
      - --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
    volumes:
      - ./db/mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql
    networks:
      - todo-network
    ports:
      - 3306:3306
  lb4:
    depends_on:
      - db
    container_name: lb4-todo-list
    image: dw1m2g25/report_dw1_m3:lb4-todo-list
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    networks:
      - todo-network
  react-admin:
    depends_on:
      - lb4
    container_name: todo-react-admin
    image: dw1m2g25/report_dw1_m3:todo-react-admin
    ports:
      - 3006:3006  
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge
